# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('products', '0002_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.School'),
        ),
    ]
