# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 02:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', null=True)),
                ('content', models.TextField(blank=True, help_text='\u7cfb\u7edf\u6d88\u606f\u5185\u5bb9', null=True)),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, b'\xe5\x85\xa8\xe4\xbd\x93\xe7\x94\xa8\xe6\x88\xb7'), (1, b'\xe9\x83\xa8\xe5\x88\x86\xe7\x94\xa8\xe6\x88\xb7')], help_text='\u6d88\u606f\u8303\u56f4', null=True)),
                ('read', models.BooleanField(default=False)),
                ('create_user', models.ForeignKey(blank=True, help_text='\u521b\u5efa\u4eba', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_news_create_user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news_classifiction',
            },
        ),
    ]
