# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-18 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='read',
        ),
        migrations.RemoveField(
            model_name='news',
            name='type',
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, help_text='\u6d88\u606f\u6807\u9898', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsclassification',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(0, b'\xe5\x85\xa8\xe4\xbd\x93\xe7\x94\xa8\xe6\x88\xb7'), (1, b'\xe9\x83\xa8\xe5\x88\x86\xe7\x94\xa8\xe6\x88\xb7')], help_text='\u6d88\u606f\u8303\u56f4', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, help_text='\u6d88\u606f\u5185\u5bb9', null=True),
        ),
    ]
