# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-18 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180418_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsClassification',
            new_name='UserNews',
        ),
        migrations.AlterModelTable(
            name='usernews',
            table='user_news',
        ),
    ]
